# COURSE INSTRUCTOR:

author:
    name:       Jacob TN Young
    github:     jacobtnyoung   # Github username for avatar

# calendly app for virtual office hours
calendly:  'https://calendly.com/jacobtnyoung/crj-507-student-meeting'



# COURSE INFO:

description:        Intro. course in social network analysis

# Header text at the top left of the website

brand:
    image:          # logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           "Social Network Analysis"    # if the above "logo:" image variable  is not set, this text logo is displayed instead
       # in the default html file add extra fav icons to header for parts II and III
       # header color set at assets/css/custom.css under default_nav and footer background-color

# Navbar at the top right of the website

header:
- title: Syllabus
  url:
- title: Course Schedule
  url: schedule/
- title: Textbook
  url: https://jacobtnyoung.github.io/sna-textbook/
- title: Resources
  url: resources/
# - title: Yellowdig
#   url: https://yellowdig.app/n/asu-online/community/6529c8c6-91a4-3875-b0e1-3e74f0d3eff5
# - title: Canvas
#  url: https://canvas.asu.edu/courses/170143
- title: Get Help
  url: help/



# GITHUB CONFIGURATIONS

url :               "https://watts-college.github.io"
baseurl:            "/crj-507-spring-2024"
course_url:         "https://Watts-College.github.io/crj-507-spring-2024/"
title:              Watts-College # don't change this

github_info:
    username:          Watts-College # Github location of the course
    branch:            master
    website-repo:      crj-507-spring-2024
    course-repo:       crj-507-spring-2024


# IGNORE THESE SETTINGS


# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/


# Social icons displayed in footer
social:
    email:
    website:
    facebook:
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:
    linkedin:
    pinterest:
    twitter:
    vimeo:
    youtube:

# Twitter share button
twitter_username:


# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   UA-123960540-3

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "layouts/datasets/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true
