---
title: "Lab 05 - Bipartite Graphs and Two-Mode Networks - INSTRUCTIONS"
date: "CRJ 507 Social Network Analysis"
output: 
  html_document:
    df_print: paged
    theme: cosmo
    highlight: haddock
    toc: yes
    toc_float: yes
    code_fold: show
    self_contained: true
---

<style>
body {
text-align: left}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```

# Introduction

The purpose of this lab is to familiarize yourself with bipartite graphs and two-mode networks in *R*. Please review the [Bipartite Graphs/Two-Mode Networks](https://jacobtnyoung.github.io/sna-textbook/ch-10-bipartite-graphs.html) chapter of the [SNA Textbook](https://jacobtnyoung.github.io/sna-textbook/index.html) as well as [Tutorial 8 - Bipartite Graphs and Two-Mode Networks in R](../tutorials/tutorial-08-bipartite-twomode.html) prior to beginning this lab.

<br>

## Part I: A Conspiracy Network

For this part of the lab, you will use data collected from [Paul Revere's Ride](https://global.oup.com/ushe/product/paul-reveres-ride-9780195098310?cc=us&lang=en&), by David Fischer. In the book, Fischer documents Reveres connections through various affiliations in locations and how these influenced history. The Paul Revere conspiracy dataset concerns relationships between 254 people and their affiliations with seven different organizations in Boston. The dataset refers to Paul Revere, who was responsible for organizing a local militia of Boston's revolutionary movement. The network is two-mode, with 254 actors and 7 organizations ("events"). We will refer to this network as the `PaulRevereNet`.

<br>

For the `PaulRevereNet` network, do the following:  

1. Plot the network using the `gplot()` function.  
2. Calculate the density of the network.
3. Interpret the density of the network.
4. Calculate the degree centrality scores for each set of nodes.  
5. Calculate the mean degree centrality scores and interpret the values.  
6. Calculate the standardized degree centrality scores for each set of nodes.  
7. Calculate the mean standardized degree centrality score.  
8. Plot the network using the standardized degree centrality scores.
9. Using the vertex attribute `people.names`, discuss which individual is most central in the network.
10. Using the vertex attribute `place.names`, discuss which location is most central in the network.

*Note*: for 9 and 10, you can access the vertex attribute using the `PaulRevereNet %v% "people.names"` and `PaulRevereNet %v% "place.names"`, respectively.

<br>

## Part II: A Kidnapping Network

For this part of the lab, you will use the Philippine Kidnappings Data which is a collection of relationships on the Abu Sayyaf Group (ASG), a violent non-state actor operating in the Southern Philippines. In particular, this data is related to the Salast movement that has been founded by Aburajak Janjalani, a native terrorist of the Southern Philippines in 1991. ASG is active in kidnapping and other kinds of terrorist attacks. The object is a two-mode network where actors are terrorist kidnappers and the terrorist events they have attended. We will refer to this as the `PhilKidnapNet` network.

For this part of the lab, use the `PhilKidnapNet` to repeat steps 1-10 in Part I. *Note*, for steps 9 and 10, the names of the nodes are stored as a vertex attribute called `vertex.names`.

<br>
<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-05-LastName.zip?raw=true) prior to beginning the lab. **The template contains code for accessing the data files**.

<br>

### Knitting to HTML

When you have completed your assignment, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload both your `.RMD` and `.HTML` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

1. Name your files using this format: **Lab-##-LastName.rmd** and **Lab-##-LastName.html**
2. Show both the solution for your code and write out your answers in the body text 

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions like `install.packages()` or `setwd()` are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect their use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  

<br>

____

<br>

##### ***Please*** report any needed corrections to the [Issues](https://github.com/Watts-College/crj-507-spring-2024/issues/new) page. Thanks!

<br>
<br>